version: '3'
services:
  # LND Testnet
  lnd:
    volumes:
      - lnd-data:/lnd
    container_name: lnd-node
    ports:
      - 10009:10009
      - 9735:9735
    build: https://github.com/tiero/docker-lnd.git
    command:
      - --bitcoin.active
      - --bitcoin.mainnet
      - --debuglevel=info
      - --bitcoin.node=neutrino
      #- --neutrino.connect=testnet1-btcd.zaphq.io
      #- --neutrino.connect=testnet2-btcd.zaphq.io
      #- --neutrino.connect=faucet.lightning.community
      - --autopilot.active
      - --rpclisten=0.0.0.0:10009
      - --tlsextradomain=lnd
    restart: unless-stopped
  coin:  
    depends_on: 
      - lnd
    container_name: coin
    build: ./coin
    restart: unless-stopped
  vault:
    depends_on: 
      - lnd
    container_name: vault
    build: ./vault
    ports:
      - 8000:8000
    restart: unless-stopped

volumes:
  lnd-data:
    external: false